version: '3.8'

services:
    nginx:
        build: ./requirements/nginx
        container_name: nginx
        # cd ..ports:
        #   - 443:443
    mariadb:
        build: ./requirements/mariadb
        container_name: mariadb
    wordpress:
        build: ./requirements/wordpress
        container_name: wordpress
