version: '3.8'

services:
    nginx:
        build: ./requirements/nginx
        container_name: nginx
        networks:
            - inception42
        ports:
            - '80:80'
            - '443:443'
        restart: always
        depends_on:
            - wordpress
        volumes:
            - wordpress_data:/var/www/html

    mariadb:
        build: ./requirements/mariadb
        container_name: mariadb
        env_file:
            - .env
        networks:
            - inception42
        volumes:
            - mariadb_data:/var/www/html
        restart: always

    wordpress:
        build: ./requirements/wordpress
        container_name: wordpress
        env_file:
            - .env
        networks:
            - inception42
        restart: always
        volumes:
            - wordpress_data:/var/www/html

    adminer:
        image: adminer
        container_name: adminer
        networks:
            - inception42
        restart: always
        ports:
            - '8080:8080'

volumes:
    wordpress_data:
    mariadb_data:

networks:
    inception42:
        name: inception42
