version: '3.8'

services:
  nginx:
    build: ./requirements/nginx
    container_name: nginx
    networks:
      - inception42
    restart: always
    # cd ..ports:
    #   - 443:443

  mariadb:
    build: ./requirements/mariadb
    container_name: mariadb
    env_file:
      - .env
    networks:
      - inception42
    #restart: always

  wordpress:
    build: ./requirements/wordpress
    container_name: wordpress
    env_file:
      - .env
    networks:
      - inception42
    restart: always

networks:
  inception42:
    name: inception42