version: '3.8'

services:
    nginx:
        build: ./requirements/nginx
        container_name: nginx
        networks:
            - inception42
        ports:
            - '80:80'
            - '443:443'
        restart: always
        depends_on:
            - wordpress
        volumes:
            - wordpress_data:/var/www/html

    mariadb:
        build: ./requirements/mariadb
        container_name: mariadb
        env_file:
            - .env
        networks:
            - inception42
        restart: always

    wordpress:
        build: ./requirements/wordpress
        container_name: wordpress
        env_file:
            - .env
        networks:
            - inception42
        restart: always
        volumes:
            - wordpress_data:/var/www/html

    redis:
        image: redis:latest
        container_name: redis
        networks:
            - inception42
        restart: always

    ftp:
        image: fauria/vsftpd
        container_name: ftp
        environment:
            - FTP_USER=myuser
            - FTP_PASS=mypassword
        networks:
            - inception42
        restart: always
        ports:
            - '21:21'
            - '21000-21010:21000-21010'

    adminer:
        image: adminer
        container_name: adminer
        networks:
            - inception42
        restart: always
        ports:
            - '8080:8080'

volumes:
    wordpress_data:
    mariadb_data:
    redis_data:
    ftp_data:

networks:
    inception42:
        name: inception42
